### ISSUE TITLE
Issue with twigfield - seomatic:3.4.33+

### ISSUE THREAD

**Issue by cloudgrayau** [nystudio107/craft-seomatic#1220]
### Describe the bug
I've just updated a really old Craft site from Craft 3.4.X to the latest 3.7.X versions, and I am unable to install Seomatic 3.4.33 or above (when twigfield was introduced). The error below only occurs when trying to access the CraftCMS backend. Reverting back to 3.4.32 is fine.

PHP Compile Error – [yii\base\ErrorException](http://www.yiiframework.com/doc-2.0/yii-base-errorexception.html)
Cannot use ::class with dynamic class name

1. in /Users/cloudgray/Sites/dev/craft/rpcgroup/vendor/nystudio107/craft-twigfield/src/services/AutocompleteService.php at line 138

                    $config = array_merge($config, $autocompleteGenerator[$autocompleteClass]);
                }
                $autocomplete = new $autocompleteClass($config);
                $name = $autocomplete->name;
                // Set up the cache parameters
                $cache = Craft::$app->getCache();
                $cacheKey = $this->getAutocompleteCacheKey($autocomplete, $config);
                $dependency = new TagDependency([
                    'tags' => [
                        self::AUTOCOMPLETE_CACHE_TAG,
                        self::AUTOCOMPLETE_CACHE_TAG . $name,
                        self::AUTOCOMPLETE_CACHE_TAG . $autocomplete::class,
                    ],
                ]);
                // Get the autocompletes from the cache, or generate them if they aren't cached
                $autocompleteItems[$name] = $cache->getOrSet($cacheKey, static function () use ($name, $autocomplete) {
                    $autocomplete->generateCompleteItems();
                    return [
                        'name' => $name,

    2. [yii\base\ErrorHandler::handleFatalError](http://www.yiiframework.com/doc-2.0/yii-base-errorhandler.html#handleFatalError()-detail)()

### Versions
- Plugin version: SEOMatic 3.4.33 or above (3.4.32 is fine).
- Craft version: Craft Solo 3.7.56

**Comment by danfathom** [comment]
I think this may be an issue with Craft. I'm also getting this error when updating craft or any any of the plugins on our site. I've raised an issue on Crafts GitHub - https://github.com/craftcms/cms/issues/12126

**Comment by i-just** [comment]
It seems to only happen if you want to update to SEOmatic 3.4.33+ if you're on PHP 7. Update works fine for PHP 8.

**Comment by angieherrera** [comment]
I ran into this issue too. I downgraded SEOmatic to 3.4.32 and it works fine.

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-twigfield/commit/bff508e2e239fd55b8a17ea56fc60db5e655f418

Released as Twigfield 1.0.15: https://github.com/nystudio107/craft-twigfield/releases/tag/1.0.15

You can update to it by doing:

```
composer update nystudio107/craft-twigfield
```

**Comment by khalwat** [comment]
Anyone who had this issue, and updated to the latest Twigfield, if you could affirm that it has fixed the issue for you, I'd appreciate you posting that here.

**Comment by cloudgrayau** [comment]
@khalwat I just checked, and it has indeed fixed the issue. Thanks!

**Comment by alanski66** [comment]
Mmm 
--
PHP 7.4.30
Craft Pro 3.7.59
SEOmatic 3.4.40
--

Ran composer update, cleared caches twice and still getting a 500 error in console on background url:
index.php?p=admin/actions/twigfield/autocomplete/index&fieldType=SeomaticExpressionField&twigfieldOptions=%7B"singleLineEditor"%3Atrue%7D

Further info: when i run the composer update 
```
composer update nystudio107/craft-twigfield
```
console reports:
```
  - Downloading nystudio107/craft-twigfield (1.0.18)
  - Downgrading nystudio107/craft-twigfield (1.0.19 => 1.0.18): Extracting archive
```
I'm confused as to which version of twigfield I have and if i need to downgrade to 1.0.15

**Comment by khalwat** [comment]
@joomkit you want the latest version. From that output, it looks like you downgraded rather than upgraded it.

Regardless, if you update to the latest SEOmatic, it doesn't use Twigfield anymore, but instead uses a new general purpose package called Code Editor
