### ISSUE TITLE
Unable to remove double title on homepage?

### ISSUE THREAD

**Issue by MattAppleton** [nystudio107/craft-seomatic#1518]
### Describe the bug
I see the site title appearing twice with a separator in my homepage 'title' tag

### To reproduce
Steps to reproduce the behaviour:
1. visit https://www.tavinstitute.org, inspect the title
2. see the following: 

`<title>The Tavistock Institute of Human Relations | The Tavistock Institute…</title>`

### Expected behaviour
I only want to see 

`<title>The Tavistock Institute of Human Relations</title>`

in SeoMatic Content SEO for my 'homepage' single I have set NO Title, and set the site name position to 'none' — but still get two titles!

### Screenshots

<img width="1216" alt="Zircon-Screenshot 2024-09-30 at 14 02 37" src="https://github.com/user-attachments/assets/786c9eef-d7cf-4c5d-95db-4932e2ecf67a">

### Versions
- Plugin version: 4.1.2
- Craft version: 4.12

**Comment by khalwat** [comment]
Probably it is treating that as an empty title, and thus is falling back on the Global SEO settings.

Can you try setting the SEO Title Source to whatever you want it to be, but keeping the rest the same?

**Comment by MattAppleton** [comment]
@khalwat  thanks for checking this...

OK, here's the results of some tests* targeting my 'homepage' single where the issue is...

**Content SEO** / SEO Title Source : _empty_  + **Global SEO** / SEO Title Source : 'Company name' = double title ❌ — should be single!?

**Content SEO** / SEO Title Source : 'Company name'  + **Global SEO** / SEO Title Source : 'Company name' = double title ❌— one should replace the other I think?!

**Content SEO** / SEO Title Source : 'Company name'  + **Global SEO** / SEO Title Source : _empty_ = single title ✅— not what I'd expect, but maybe I'm misunderstanding how the plugin works...  the 'dashboard' seems to suggest emptying the SEO Title is not ideal!!

<img width="363" alt="Mica_Screenshot 2024-10-01 at 05 29 52" src="https://github.com/user-attachments/assets/77564972-7066-46b8-aedf-b8dcc2f16aee">




* the 'Site name' field in 'Identity Settings' has the 'company name' filled in (obvs!)

**Comment by khalwat** [comment]
Can you update to the latest version of SEOmatic? There was a caching bug that affected only homepage singles that was addressed

**Comment by MattAppleton** [comment]
Realised I was actually running 4.1.4 which is I think the latest I can run on Craft 4?

<img width="616" alt="Mica_Screenshot 2024-10-01 at 07 49 49" src="https://github.com/user-attachments/assets/9d39d54c-c069-46f9-8fec-436fbf3aeeb6">


Anyway, double checked that, saved, cleared ALL caches inc. Blitz, and trying what I think should be right, I still get these two scenarios on the 'homepage'

Content SEO / SEO Title Source : _empty_ + Global SEO / SEO Title Source : 'Company name' = double title ❌ — should be single!?

Content SEO / SEO Title Source : 'Company name' + Global SEO / SEO Title Source : 'Company name' = double title ❌— one should replace the other I think?!

**Comment by khalwat** [comment]
So I'm trying to reproduce this here, but I'm unable to.

Here's what I have the Global SEO set to:

<img width="1174" alt="Screenshot 2024-10-01 at 15 22 06" src="https://github.com/user-attachments/assets/bd672c19-cbc8-49f1-b6fd-826f6425e27c">

And here's what I have the Content SEO settings for the Homepage single set to:

<img width="1174" alt="Screenshot 2024-10-01 at 15 22 43" src="https://github.com/user-attachments/assets/aa74e7b3-1b6a-492f-bad7-0a4b41fd29ff">

...and the result is what I'd expect, just **Homepage**:

<img width="510" alt="Screenshot 2024-10-01 at 15 23 36" src="https://github.com/user-attachments/assets/3f3a3797-506c-4e01-83b8-59768594a192">

Do you have an SEO Settings field in the mix here that could be overriding something?

Can you show me screenshots analogous to the ones I've shown above?

**Comment by MattAppleton** [comment]
@khalwat  sure... I'm afraid the tab (and Google preview still give me a double entry...)

(im wondering if this has something to do with the fact that this is a MULTISITE setup?

<img width="1106" alt="Mica_Screenshot 2024-10-01 at 23 06 00" src="https://github.com/user-attachments/assets/dcb9ae1d-ef9f-4140-b00b-b5f9e163185b">

<img width="1099" alt="Mica_Screenshot 2024-10-01 at 23 07 19" src="https://github.com/user-attachments/assets/3832ecac-e182-4acf-b189-02dcbf070c15">

**Comment by khalwat** [comment]
Your second screenshot is cut off at a rather critical place :)

**Comment by khalwat** [comment]
And yes, it could be that it's multi-site, there are separate settings for each site. Are you sure you're changing the Content SEO settings appropriately for each site?

**Comment by MattAppleton** [comment]
Hi @khalwat — you are  right, dodgy screenshots there :)

Anyway, think I just found the culprit — the single settings for 'homepage'...

For some reason we had it set like this

<img width="1353" alt="Mica_Screenshot 2024-10-02 at 21 50 32" src="https://github.com/user-attachments/assets/37f9cc73-3230-475c-b3ab-15ad76ab1b07">


Switching it to this 'homepage' setting works

<img width="1354" alt="Mica_Screenshot 2024-10-02 at 21 50 40" src="https://github.com/user-attachments/assets/cc77230f-f651-4a57-8497-3d7a6df70ef6">

in conjunction with


<img width="1362" alt="Mica_Screenshot 2024-10-02 at 21 53 05" src="https://github.com/user-attachments/assets/82779257-dc29-4b7a-91ea-3760f4950385">

**Comment by MattAppleton** [comment]
thanks for your time there @khalwat — feeling slightly sheepish now!

**Comment by khalwat** [comment]
Ah makes sense, glad you got it sorted!
